### ISSUE TITLE
User input of solar indices for IRI

### ISSUE THREAD

**Issue by tpl2go** [timduly4/pyglow#31] opened 2017-08-04 06:54 UTC
Hello,

I am wondering if there is a way to specify a user input of R12 or F10.7 for IRI instead of relying on dates and historical data

**Comment by timduly4** [comment] 2017-08-04 14:13
@tpl2go ,

You can make an instance of the `Point` class with optional argument for a boolean of `user_ind = True` to set your own indices for the models, but the issue is that this will not work for IRI because the model runs its own internal `readapf107()` Fortran subroutine (see [here](https://github.com/timduly4/pyglow/blob/master/pyglow/pyglow.py#L150)) to calculate the F10.7 values.

Tim

**Comment by bzossi** [comment] 2018-11-01 20:10
Hi.
I think that force F10.7 input does not work optimally. The F2 layer is not changing as it should with F10.7
I make height profile of Ne with pt.f107=0 (and pt.f107a=0) and pt.f107=200 (pt.f107a=200)
![f107](https://user-images.githubusercontent.com/30929997/47876357-e1d08580-ddf7-11e8-9787-22060283b927.png)
Where red line is F107=200.

But testing with IRIweb from: 
https://ccmc.gsfc.nasa.gov/modelweb/models/iri2016_vitmo.php
For the same day and time forcing F107=200
![f107 200](https://user-images.githubusercontent.com/30929997/47876501-36740080-ddf8-11e8-86ee-ae0c003bc382.gif)

There is an order of magnitude of difference at 250 km.
Maybe I'm doing something wrong

**Comment by timduly4** [comment] 2018-11-02 14:42
@bzossi Could you post the code you use to derive the plot?  That might be helpful to understand what the problem might be.

**Comment by timduly4** [comment] 2018-11-10 17:54
@bzossi Let's back up a bit before zeroing in on the problem.  Can you compare a run of IRI using the IRIweb compared against pyglow, without using user-defined F107 and F107A values?  How do the results compare?

**Comment by bzossi** [comment] 2018-11-12 12:01
@timduly4 
I did some runs, and it seems that layer F2 works differently in pyglow and IRIweb, curious.
I downloaded output of the IRIweb for the same days, time, location and plot with pyglow out using the default settings
![2008](https://user-images.githubusercontent.com/30929997/48345990-66bd6980-e658-11e8-90ce-93dae811946f.png) ![2001](https://user-images.githubusercontent.com/30929997/48345997-691fc380-e658-11e8-9001-c88a104571d7.png)

I'll check it under other conditions, just in case.

**Comment by timduly4** [comment] 2018-11-12 16:39
@bzossi , interesting-- the plot thickens.  The next thing we need to investigate are the `jf` switches within IRI, and there are a myriad of them.  We've tried to mimic a "standard" IRI call with the switches listed here (note the indexing difference between Python and Fortran, here):

https://github.com/timduly4/pyglow/blob/master/src/pyglow/pyglow.py#L216

However, I am unsure what switches are utilized for the IRIweb.

Also note that we found a bug relating to user defined indices (see: https://github.com/timduly4/pyglow/issues/34), that was subsequently fixed in the IRI code.  I was hoping that without defining the indices, we could remove that variable from the debugging, but it looks like the profiles are different even with the default indices.

**Comment by bzossi** [comment] 2018-11-12 19:47
@timduly4
It seems like a thing of jf switches.
IRIWeb has set the F-height peak AMTB-2013, but in the source code is SHU-2015 (jf(39 - 40))
Changing this on the iriweb, the profiles look very similar.
![new](https://user-images.githubusercontent.com/30929997/48371080-b2dcce00-e699-11e8-8303-935635673cb9.png)
Pyglow is working good, the web version confused me.

**Comment by timduly4** [comment] 2018-11-12 20:21
@bzossi , great to hear that the issue is resolved.  It's good that IRI is a "standard model," but as we've seen, there are many different parameterization options that can result in a very different ionospheric specification, which can lead to confusion!

Did you find an online resource that described the configuration of IRI for running on IRIWeb?  If so, could you post it for reference?  Thanks.

**Comment by bzossi** [comment] 2018-11-13 11:55
I followed the Fortran codes and compared them to the default web. The optional configurations on the web are:![optional](https://user-images.githubusercontent.com/30929997/48411723-2c6bcf00-e721-11e8-98a3-ea90871607e1.png)
The slow way.

**Comment by timduly4** [comment] 2018-11-13 16:22
@bzossi Thanks, we'll keep this on record in case any other related issues arise.  I'll close for now 👍

**Closed by timduly4** 2018-11-13 16:22 UTC
