### ISSUE TITLE
ERROR WHEN IMPORT PYGLOW 

### ISSUE THREAD

**Issue by Armando123x** [timduly4/pyglow#145] opened 2022-03-05 22:19 UTC
I have a virtual ven with Python 3.7. The version Numpy is 1.21.5, but I have the next problem when I import pyglow.

> >>> from pyglow import pyglow
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/arx/anaconda3/envs/py37/lib/python3.7/site-packages/pyglow/__init__.py", line 2, in <module>
>     from .pyglow import __version__  # noqa F401
>   File "/home/arx/anaconda3/envs/py37/lib/python3.7/site-packages/pyglow/pyglow.py", line 17, in <module>
>     from .iri import IRI  # noqa E402
>   File "/home/arx/anaconda3/envs/py37/lib/python3.7/site-packages/pyglow/iri.py", line 4, in <module>
>     from iri12py import iri_sub as iri12
> ImportError: cannot import name 'iri_sub' from 'iri12py' (/home/arx/anaconda3/envs/py37/lib/python3.7/site-packages/iri12py.cpython-37m-x86_64-linux-gnu.so)

**Comment by bharding512** [comment] 2022-03-15 21:55
Did IRI install correctly?

**Comment by Vaylyn** [comment] 2022-06-01 08:40
I had the same issue when using NumPy 1.22. As it turned out you have to be careful about which NumPy version you use. With NumPy 1.18 the error didn't appear. I haven't testet the versions in between, but using NumPy 1.18 should resolve your issue.

@bharding512 Maybe you could add these version restrictions to the requirements file to avoid future issues.

**Comment by bharding512** [comment] 2022-06-01 17:11
I'd prefer to solve the underlying problem. This issue appears to be a duplicate of #139, so I'm closing it. Please re-open if I misunderstood something. As always, ideas and PRs are very welcome.

**Closed by bharding512** 2022-06-01 17:11 UTC
